=== anrabkov/task2/src/main/resources/schema/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/papers"
        xmlns:tns="http://www.example.org/papers"
        elementFormDefault="qualified">
    <element name="papers">
        <complexType>
            <sequence>
                <element ref="tns:paper" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="paper">
        <sequence>
            <element name="title" type="string" />
            <element name="number-of-pages" type="tns:numberOfPages" />
            <element name="price" type="tns:price" />
            <element name="monthly" type="boolean" />
            <element name="color" type="boolean" />
            <element name="publication-date" type="gMonthDay" />
        </sequence>
        <attribute name="id" type="tns:paperID" use="required" />
        <attribute name="note" use="optional" default="empty"  />
    </complexType>


    <complexType name="glossyPaper">
        <complexContent>
            <extension base="tns:paper">
                <sequence>
                    <element name="glossy-paper-type" type="tns:glossyPaperType" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="notGlossyPaper">
        <complexContent>
            <extension base="tns:paper">
                <sequence>
                    <element name="not-glossy-paper-type" type="tns:notGlossyPaperType" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="paperID">
        <restriction base="ID">
            <pattern value="\w{1,30}" />
        </restriction>
    </simpleType>

    <simpleType name="price">
        <restriction base="unsignedInt">
            <minInclusive value="0" />
            <maxInclusive value="100" />
        </restriction>
    </simpleType>

    <simpleType name="numberOfPages">
        <restriction base="unsignedInt">
            <minInclusive value="1" />
            <maxInclusive value="200" />
        </restriction>
    </simpleType>

    <simpleType name="glossyPaperType">
        <restriction base="string">
            <enumeration value="BOOKLET" />
            <enumeration value="MAGAZINE" />
        </restriction>
    </simpleType>

    <simpleType name="notGlossyPaperType">
        <restriction base="string">
            <enumeration value="NEWSPAPER" />
            <enumeration value="MAGAZINE" />
        </restriction>
    </simpleType>

    <element name="paper" type="tns:paper" abstract="true" />
    <element name="glossy-paper" type="tns:glossyPaper" substitutionGroup="tns:paper" />
    <element name="not-glossy-paper" type="tns:notGlossyPaper" substitutionGroup="tns:paper" />

</schema>

=== anrabkov/task2/src/main/resources/data/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:tns ="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/papers"
         tns:schemaLocation="http://www.example.org/papers ../schema/schema.xsd">


    <glossy-paper id="b1" note="for everyone">
        <title>Example Glossy Paper</title>
        <number-of-pages>3</number-of-pages>
        <price>2</price>
        <monthly>false</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>BOOKLET</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="b2" note="for everyone">
        <title>Example Glossy Paper</title>
        <number-of-pages>3</number-of-pages>
        <price>2</price>
        <monthly>false</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>BOOKLET</glossy-paper-type>
    </glossy-paper>


    <glossy-paper id="b3" note="for everyone">
        <title>Example Glossy Paper</title>
        <number-of-pages>3</number-of-pages>
        <price>2</price>
        <monthly>false</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>BOOKLET</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="b4" note="for everyone">
        <title>Example Glossy Paper</title>
        <number-of-pages>3</number-of-pages>
        <price>2</price>
        <monthly>false</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>BOOKLET</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="b5" note="for everyone">
        <title>Example Glossy Paper</title>
        <number-of-pages>3</number-of-pages>
        <price>2</price>
        <monthly>false</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>BOOKLET</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="b6" note="for everyone">
        <title>Example Glossy Paper</title>
        <number-of-pages>3</number-of-pages>
        <price>2</price>
        <monthly>false</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>BOOKLET</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="m1" note="for adults">
        <title>Example Glossy Paper</title>
        <number-of-pages>25</number-of-pages>
        <price>10</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>MAGAZINE</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="m2" note="for adults">
        <title>Example Glossy Paper</title>
        <number-of-pages>25</number-of-pages>
        <price>10</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>MAGAZINE</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="m3" note="for adults">
        <title>Example Glossy Paper</title>
        <number-of-pages>25</number-of-pages>
        <price>10</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>MAGAZINE</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="m4" note="for adults">
        <title>Example Glossy Paper</title>
        <number-of-pages>25</number-of-pages>
        <price>10</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>MAGAZINE</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="m5" note="for adults">
        <title>Example Glossy Paper</title>
        <number-of-pages>25</number-of-pages>
        <price>10</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>MAGAZINE</glossy-paper-type>
    </glossy-paper>

    <glossy-paper id="m6" note="for adults">
        <title>Example Glossy Paper</title>
        <number-of-pages>25</number-of-pages>
        <price>10</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <glossy-paper-type>MAGAZINE</glossy-paper-type>
    </glossy-paper>

    <not-glossy-paper id="n1">
        <title>Example Not Glossy Paper</title>
        <number-of-pages>10</number-of-pages>
        <price>4</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <not-glossy-paper-type>NEWSPAPER</not-glossy-paper-type>
    </not-glossy-paper>


    <not-glossy-paper id="n2">
        <title>Example Not Glossy Paper</title>
        <number-of-pages>10</number-of-pages>
        <price>4</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <not-glossy-paper-type>NEWSPAPER</not-glossy-paper-type>
    </not-glossy-paper>

    <not-glossy-paper id="n3">
        <title>Example Not Glossy Paper</title>
        <number-of-pages>10</number-of-pages>
        <price>4</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <not-glossy-paper-type>NEWSPAPER</not-glossy-paper-type>
    </not-glossy-paper>

    <not-glossy-paper id="n4">
        <title>Example Not Glossy Paper</title>
        <number-of-pages>10</number-of-pages>
        <price>4</price>
        <monthly>true</monthly>
        <color>true</color>
        <publication-date>--02-25</publication-date>
        <not-glossy-paper-type>NEWSPAPER</not-glossy-paper-type>
    </not-glossy-paper>



</papers>
